on:
  push:
  #  branches:
  #    - master
  pull_request:
    branches:
      - main

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:latest

    name: bioconductor_docker:latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up renv
        run: |
          install.packages('renv')
          renv::install(c('BiocManager', 'remotes'))
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          renv::restore()
        shell: Rscript {0}

      - name: Render site
        run: |
          rmarkdown::render(input = "index.Rmd")
        shell: Rscript {0}

      - name: Prepare files to deploy
        run: |
          mkdir _site
          cp -r img libs my-theme.css index.html _site/

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          apt-get update && apt-get -y install rsync

      - name: Deploy 🚀
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
